version: "3.9"

services:
  php:
    build: ./backend
    ports:
      - "8001:80"

  python:
    build: ./falcon_fw
    command: ["waitress-serve", "--port=8000", "wsgi:app"]
    ports:
      - "8000:8000"
    depends_on:
      - php